#使用feign负载均衡作为消费者
server:
  port: 1010
  servlet:
    context-path: /eureka-feign-consumer

spring:
  application:
    name: eureka-feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/