server:
  port: 9090
  servlet:
    context-path: /eureka-consumer
spring:
  application:
    name: eureka-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
